---
name: CI

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: read
  security-events: write

jobs:
  workflows:
    uses: einschmidt/workflows/.github/workflows/app-ci.yaml@6e89b387b7c75b60847138578ce5140bdac2923a # v0.1.1
