---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

permissions:
  issues: write

jobs:
  workflows:
    uses: einschmidt/workflows/.github/workflows/labels.yaml@6e89b387b7c75b60847138578ce5140bdac2923a # v0.1.1
