---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

permissions: {}

jobs:
  workflows:
    uses: einschmidt/workflows/.github/workflows/pr-labels.yaml@6e89b387b7c75b60847138578ce5140bdac2923a # v0.1.1
